# Generated by Django 4.2.1 on 2025-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_app', '0014_product_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionuser',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='live', max_length=100, null=True),
        ),
    ]
